name: mobx_study
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  sqflite: ^2.3.3+1
  get_it: ^7.0.0
  equatable: ^2.0.0
  path: ^1.8.0
  uuid: ^3.0.0
  flutter_svg: ^2.0.10+1
  sqflite_common_ffi: ^2.3.3
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icons8-check-200(-xxxhdpi).png"

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/undraw_completing_re_i7ap.svg
    - assets/illustrations/undraw_to_do_re_jaef.svg
    - assets/illustrations/undraw_checklist__re_2w7v.svg
